=== GIDSOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-PHP/Resources/xsd/MedMij_Whitelist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--File version: 2-->
<xs:schema xmlns:wl="xmlns://afsprakenstelsel.medmij.nl/whitelist/release2/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="xmlns://afsprakenstelsel.medmij.nl/whitelist/release2/" elementFormDefault="qualified">
    <!--Root element-->
    <xs:element name="Whitelist" type="wl:Whitelist"></xs:element>
    <!--SimpleTypes-->
    <xs:simpleType name="DatumTijdType">
        <xs:restriction base="xs:dateTime">
            <xs:pattern value=".{20,}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="PositiefnummerType">
        <xs:restriction base="xs:positiveInteger"></xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="HostnameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(([a-z0-9])([a-z0-9-])*(\.))+([a-z0-9])([a-z0-9-])*([a-z0-9])"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <!--ComplexTypes-->
    <xs:complexType name="Whitelist">
        <xs:sequence>
            <xs:element name="Tijdstempel" type="wl:DatumTijdType"></xs:element>
            <xs:element name="Volgnummer" type="wl:PositiefnummerType"></xs:element>
            <xs:element name="MedMijNodes" type="wl:MedMijNodes">
                <xs:unique name="Unieke-MedMijNode">
                    <xs:selector xpath="wl:MedMijNode"/>
                    <xs:field xpath="."/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MedMijNodes">
        <xs:sequence>
            <xs:element name="MedMijNode" type="wl:HostnameType" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== GIDSOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-PHP/Resources/examples/MedMij_Whitelist_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--File version: 2-->
<Whitelist xmlns="xmlns://afsprakenstelsel.medmij.nl/whitelist/release2/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="xmlns://afsprakenstelsel.medmij.nl/whitelist/release2/ MedMij_Whitelist.xsd">
    <Tijdstempel>2018-04-16T10:43:41+01:00</Tijdstempel>
    <Volgnummer>28654</Volgnummer>
    <MedMijNodes>
        <MedMijNode>specimen-stelselnode.medmij.nl</MedMijNode>
        <MedMijNode>medmij.deenigeechtepgo.nl</MedMijNode>
        <MedMijNode>pgocluster68.personalhealthprovider.net</MedMijNode>
        <MedMijNode>78834.umcharderwijk.nl</MedMijNode>
        <MedMijNode>medmij.za982.xisbridge.net</MedMijNode>
        <MedMijNode>medmij.za983.xisbridge.net</MedMijNode>
        <MedMijNode>medmij.xisbridge.net</MedMijNode>
        <MedMijNode>rcf-rso.nl</MedMijNode>
    </MedMijNodes>
</Whitelist>
